export const data = {
	verbs: [
		'to diss',
		'to ogle',
		'to jeopardize',
		'to speculate',
		'to hustle',
		'to dare',
		'to suspect',
		'to act',
		'to object',
		'to quarrel',
		'to beware',
		'to treat',
		'to yawn',
		'to mention',
		'to interrupt',
		'to occur',
		'to swindle',
		'to breed',
		'to bold',
		'to bust',
		'to ditch'
 	], 
	nouns: [
		'Master key',
		'Teetolater',
		'Booze',
		'Liquor',
		'violation',
		'moniker',
		'jerk',
		'pastry',
		'hot stuff',
		'tough stuff',
		'sprout',
		'staff',
		'bagpipe',
		'malarkey',
		'grocery',
		'mankind',
		'cop out',
		'mosquito',
		'mindset',
		'coupling',
		'seal',
		'cattle',
		'alarm',
		'handful',
		'latency',
		'precinct',
		'tan',
		'grease',
		'squeak'
	],
	adjectives: [
		'avid',
		'lousy',
		'gross',
		'wrong',
		'cruel',
		'perfidious',
		'tough',
		'mad',
		'anticipating',
		'agile',
		'moonshine',
		'moonlighting',
		'redundant',
		'sluggish',
		'handsome',
		'capricious',
		'fastidious',
		'heavy-duty'
	],
	bundles: [
		'around',
		'personally',
		'between',
		'among',
		'in the middle',
		'ahead/forward',
		'ahead of time',
		'behind',
		'back',
		'especially',
		'fortunately',
		'unfortunately',
		'again',
		'against',
		'at least'
	],
	phrases: [
		'To get the munchies',
		'for crying out loud!',
		'What does it have to do with...',
		'Fine, but isn\'t mine',
		'That\'s the way the cookie crumbles',
		'Blessing in disguise',
		'Look who\'s talking',
		'Good for me',
		'Well done',
		'To give the boot',
		'Get a grip',
		'I am stoked',
		'You bet',
		'You\'re asking yet!',
		'Get by',
		'my cup of tea',
		'buy stuff',
		'it\'s a no brainer',
		'How you slice it',
		'Beat around the bush',
		'Don\'t give it a thought',
		'Pull out all the stops',
		'Can\'t know the ass from the elbow',
		'Get the lay of the land',
		'Man supposes - God disposes',
		'Wishful thinking',
		'Pie in the sky',
		'To be on the fence about',
		'The best is yet to come',
		'It ain\'t over till the fat lady sings',
		'Cambrian explosion',
		'Hit or miss',
		'Jump the gun',
		'Holly smokes',
		'Give it a shot',
		'On the home stretch',
		'It\'s just a matter of time',
		'To follow suit',
		'Change the suit',
		'Follow my suit',
		'Red-handed',
		'Right away?',
		'Ace in sleeve',
		'Move your ass',
		'Poker face',
		'To trump up',
		'Ace on base',
		'We try the best you know the rest',
		'Ditch and switch',
		'Come down to the following',
		'Come what may',
		'To have let yourself go',
		'Shoe in for',
		'No harm in trying',
		'Squeaky wheel gets the grease'
	] 
};