export const data = {
	verbs: [
		'to diss',
		'to ogle',
		'to jeopardize',
		'to speculate',
		'to hustle',
		'to dare',
		'to suspect',
		'to act',
		'to object',
		'to quarrel',
		'to beware',
		'to treat',
		'to yawn',
		'to mention',
		'to interrupt',
	],
	bundles: [
		'around',
		'personally',
		'between',
		'among',
		'in the middle',
		'ahead/forward',
		'ahead of time',
		'behind',
		'back',
		'especially',
		'fortunately',
		'unfortunately',
		'again',
		'against',
		'at least'
	],
	phrases: [
		'to get the munchies',
		'for crying out loud!',
		'What does it have to do with...',
		'Fine, but isn\'t mine',
		'That\'s the way the cookie crumbles',
		'Blessing in disguise',
		'Look who\'s talking',
		'Good for me',
		'Well done',
		'To give the boot',
		'Get a grip',
		'I am stoked',
		'You bet',
		'You\'re asking yet!',
	]
};